- name: Install Ldapserver
  yum:
    name: "{{ item }}"
  with_items: "{{ ldap_dependent_packages }}"
  tags: a1

- name: Generate the token
  expect:
    command: slappasswd
    responses:
      (?i)password: "{{ admin_passwd }}"
  register: result

- name: Test register
  debug: msg="{{ result.stdout_lines[2] }}"

- name: Configure LDAP database
  shell: cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG && chown ldap:ldap /var/lib/ldap/DB_CONFIG

- name: Modify LDAP configuration file
  shell: sed -i -e 's/cn=Manager/cn={{ dn_cn }}/g' -e 's/dc=my-domain/dc={{ dn_dc }}/g' {{ ldap_config_route }}/olcDatabase\=\{1\}monitor.ldif && \ 
         sed -i -e 's/cn=Manager/cn={{ dn_cn }}/g' -e 's/dc=my-domain/dc={{ dn_dc }}/g' {{ ldap_config_route }}/olcDatabase\=\{2\}hdb.ldif && \ 
         echo "olcRootPW:{{ result.stdout_lines[2] }}" >> {{ ldap_config_route }}/olcDatabase\=\{2\}hdb.ldif
  tags: t1

- name: Detection profile
  shell: slaptest -u
  register: result
  changed_when: "'succeeded' in result.stdout"
  failed_when: "result.rc != 0"
  become: true

- name: Start the ldap service
  service:
    name: slapd
    state: started
    enabled: yes

- name: Copy the script
  template:
    src: add_config_to_ldif.yml.j2
    dest: /root/add_config_to_ldif.sh

- name: Configuration is added to the schema  
  shell: chmod +x /root/add_config_to_ldif.sh && /root/add_config_to_ldif.sh
  tags: t2

- name: Generating database basic framework
  shell: cd /usr/share/migrationtools && \
         sed -i 's/padl.com/{{ dn_dc }}.com/' migrate_common.ph && \
         sed -i 's/dc=padl/dc={{ dn_dc }}/' migrate_common.ph && \
         ./migrate_base.pl > /tmp/base.ldif

- name: Import base.ldif into the database
  expect:
    command: ldapadd -x -W -D "cn={{ dn_cn }},dc={{ dn_dc }},dc=com" -f /tmp/base.ldif 
    responses:
      (?i)password: "846869"
  register: result2
  tags: t3

- name: test result2
  debug:
    msg: "{{ result2 }}"
