---
- name: Install and set up openldap service
  include_tasks: install_openldap.yml
  when: ansible_distribution == 'CentOS'

- name: Install and set up phpldapadmin service 
  include_tasks: install_phpldapadmin.yml
  when: ansible_distribution == 'CentOS'
